In [50]:
import pandas as pd 
import numpy as np

# 부산항 컨테이너 성장에서 환적의 기여 구조 파악

In [51]:
df=pd.read_csv('cct.csv', encoding='cp949')

df.head()

     연도   컨물동량    증감율  수출입소계    수입    수출   환적소계  환적점유율  환적증감율
0  2013  17686  3.750   8934  4424  4509   8748 49.470  7.380
1  2014  18683  5.640   9254  4596  4658   9429 50.470  7.780
2  2015  19469  4.200   9364  4714  4650  10105 51.910  7.170
3  2016  19456 -0.060   9620  4801  4819   9836 50.550 -2.670
4  2017  20493  5.330  10186  5042  5144  10225 49.900  3.960

In [52]:
print(df.shape)
print(df.columns.to_list())
print(df.dtypes)
print(df.info())

(13, 9)
['연도', ' 컨물동량', '증감율', '수출입소계', '수입', '수출', '환적소계', '환적점유율', '환적증감율']
연도         int64
 컨물동량      int64
증감율      float64
수출입소계      int64
수입         int64
수출         int64
환적소계       int64
환적점유율    float64
환적증감율    float64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      13 non-null     int64
 1    컨물동량   13 non-null     int64
 2   증감율     13 non-null     float64
 3   수출입소계   13 non-null     int64
 4   수입      13 non-null     int64
 5   수출      13 non-null     int64
 6   환적소계    13 non-null     int64
 7   환적점유율   13 non-null     float64
 8   환적증감율   13 non-null     float64
dtypes: float64(3), int64(6)
memory usage: 1.0 KB
None

In [53]:
df.describe()

,연도,컨물동량,증감율,수출입소계,수입,수출,환적소계,환적점유율,환적증감율
count,13.000,13.000,13.000,13.000,13.000,13.000,13.000,13.000,13.000
mean,"2,019.000","21,422.154",2.992,"10,071.231","5,014.000","5,057.077","11,343.846",52.768,4.395
std,3.894,"2,169.440",2.771,625.807,310.466,317.514,"1,591.691",2.234,4.460
min,"2,013.000","17,686.000",-2.770,"8,934.000","4,424.000","4,509.000","8,748.000",49.470,-4.130
25%,"2,016.000","19,469.000",1.520,"9,620.000","4,801.000","4,819.000","10,105.000",50.550,2.100
50%,"2,019.000","21,824.000",4.040,"10,233.000","5,117.000","5,144.000","11,638.000",52.920,4.400
75%,"2,022.000","22,706.000",5.330,"10,433.000","5,208.000","5,225.000","12,273.000",54.050,7.380
max,"2,025.000","24,882.000",5.700,"10,904.000","5,409.000","5,495.000","14,097.000",56.700,11.770

In [54]:
# 연도별 환적점유율
trans_share = df[['연도', '환적점유율']]

trans_share

      연도  환적점유율
0   2013 49.470
1   2014 50.470
2   2015 51.910
3   2016 50.550
4   2017 49.900
5   2018 52.760
6   2019 52.920
7   2020 55.080
8   2021 54.050
9   2022 53.290
10  2023 53.590
11  2024 55.300
12  2025 56.700

In [55]:
print(df.columns)
df.columns = df.columns.str.strip()

Index(['연도', ' 컨물동량', '증감율', '수출입소계', '수입', '수출', '환적소계', '환적점유율', '환적증감율'], dtype='str')

In [56]:
# 환적 기여율

#전년 대비 증가량
df['전체증가량'] = df['컨물동량'].diff()
df['환적증가량'] = df['환적소계'].diff()

# 환적 기여율
df['환적기여율(%)'] = (
    df['환적증가량'] / df['전체증가량'] * 100
).round(2)

df[['연도', '전체증가량', '환적증가량', '환적기여율(%)']]

      연도     전체증가량     환적증가량  환적기여율(%)
0   2013       NaN       NaN       NaN
1   2014   997.000   681.000    68.300
2   2015   786.000   676.000    86.010
3   2016   -13.000  -269.000 2,069.230
4   2017 1,037.000   389.000    37.510
5   2018 1,170.000 1,204.000   102.910
6   2019   329.000   209.000    63.530
7   2020  -168.000   382.000  -227.380
8   2021   882.000   253.000    28.680
9   2022  -628.000  -507.000    80.730
10  2023 1,076.000   642.000    59.670
11  2024 1,248.000 1,088.000    87.180
12  2025   480.000   601.000   125.210

전체 물동량이 증가한 연도 대부분에서 환적기여율이 높은 수준을 보임
일부 연도에는 100%를 넘어 수출입 물동량 감소를 환적 증가가 상쇄한 것으로 나타남
따라서 부산항의 물동량 성장은 환적 물동량 증가에 크게 의존하는 구조라고 볼 수 있다.

In [57]:
#환적과 수출입 중 누가 더 많이 성장했는지

#수출입증감률
df['수출입증감률'] = (
    df['수출입소계'].pct_change() * 100
).round(2)

df[['연도', '수출입증감률', '환적증감율']]

      연도  수출입증감률  환적증감율
0   2013     NaN  7.380
1   2014   3.580  7.780
2   2015   1.190  7.170
3   2016   2.730 -2.670
4   2017   5.880  3.960
5   2018   0.460 11.770
6   2019   1.180  1.830
7   2020  -5.310  3.280
8   2021   6.420  2.100
9   2022  -1.170 -4.130
10  2023   4.200  5.500
11  2024   1.490  8.770
12  2025  -1.090  4.400

2014~2025년 부산항은 수출입보다 환적 물동량의 성장률이 전반적으로 높게 나타남
수출입이 감소한 시기에도 환적이 증가하는 모습을 보여 부산항의 물동량 성장이 환적을 중심으로 이루어지는 경향을 확인할 수 있음